name: 'Build'

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup node 16
        uses: actions/setup-node@v3
        with:
          node-version: '116'

      - name: install
        run: npm install

      - name: build
        run: npm run build

      - name: test
        run: npm test

      - name: format check
        run: npm run format-check

      - uses: codecov/codecov-action@v3
        with:
          file: ./coverage/clover.xml
